### ISSUE TITLE
When reloading the website the Subvod turns into a gray playbutton.

### ISSUE THREAD

**Issue by Certifa** [besuper/TwitchNoSub#1]
When trying to reload an video from an sub only streamer I get this. 
![Screenshot 2022-05-10 193743](https://user-images.githubusercontent.com/74216860/167689170-7522b0c9-617f-4d09-b679-af95f4e9d44f.png)

**Comment by besuper** [comment]
The API is still working. Try with another navigator, or maybe the video is old. You can also check if there was a network error, the API request blocked, an extension that blocked the request... 

You can send me the video link, I'll check it on my side

**Comment by Certifa** [comment]
Oh yeah thanks man, I'll send the link here.

" https://www.twitch.tv/videos/1475194277 "

The twitch channel is Dutch tho, idk if that would be the problem.

**Comment by besuper** [comment]
I tried this VOD but it seems the extension doesn't work on the entire channel. Don't know why the method to watch sub-only VODs doesn't work on this specific channel. There is no fix available for now sorry.

**Comment by skripter888** [comment]
doesnt work on this channel either https://www.twitch.tv/videos/1509279413

**Comment by besuper** [comment]
I don't think this issue is the same as the author. It's more related to the issue https://github.com/besuper/TwitchNoSub/issues/7

**Comment by test2a** [comment]
i suspect as @besuper is saying, i tried this with old videos like a month or two old and i got this same grey play button. on fresh ones, it works.

so, can we "detect" if the link is dead so that the user can be informed about it?

**Comment by besuper** [comment]
> i suspect as @besuper is saying, i tried this with old videos like a month or two old and i got this same grey play button. on fresh ones, it works.
> 
> so, can we "detect" if the link is dead so that the user can be informed about it?

This is a good theory but this is specific to the channel. If you try a recent VOD of this channel it will not work. I don't know why but it's impossible to fetch VOD for some channels.

**Comment by besuper** [comment]
This issue should be fixed with commit https://github.com/besuper/TwitchNoSub/commit/4b78730ec5fd412eb3dd58ee67221e03e0e62676. The problem was that VODs have a different broadcast type, and the extension only supported the "archive" type. The entire twitch channel has "highlight" VOD type. Stream URLs are different between types.
