### ISSUE TITLE
Chrome rip

### ISSUE THREAD

**Issue by ElementShadow** [besuper/TwitchNoSub#101]
**Describe the bug**
plugin stop working still show only for subs.

**VOD / Channel link**
[The url where you encountered the error](https://www.twitch.tv/videos/2116874106?filter=archives&sort=time)

**Browser**
Chrome / firefox

**Additional context**
Clearing cookie's dont help, also did try firefox same issue

**Comment by MathieuPaillart** [comment]
Same

**Comment by mikolak6135** [comment]
when you clear the cookies, it will work but you have to do it every time

**Comment by ElementShadow** [comment]
@mikolak6135 no, its not working in chrome

**Comment by besuper** [comment]
Please update to https://github.com/besuper/TwitchNoSub/releases/tag/0.7.1
