### ISSUE TITLE
7.1 flagged by windows defender

### ISSUE THREAD

**Issue by RayanK95** [besuper/TwitchNoSub#103]
New release flagged as Trojan by Windows Defender (Trojan:Script/Wacatac.B!ml)

**Comment by Endymi0n74** [comment]
not here...

**Comment by RayanK95** [comment]
Anyone else? 7.0 does not get flagged/blocked for me

**Comment by Plum02** [comment]
Same for me 7.1 flagged

**Comment by mehhxyeah** [comment]
yup same here

**Comment by besuper** [comment]
Hi, it's false positive from windows defender. I don't know why its flagged. However if you don't want to install the extension, you can use the [userscript](https://raw.githubusercontent.com/besuper/TwitchNoSub/master/userscript/twitchnosub.user.js)
