### ISSUE TITLE
7.1 seemingly not working anymore

### ISSUE THREAD

**Issue by Undefined3301** [besuper/TwitchNoSub#104]
**Describe the bug**
It seems like the extension isn't unlocking sub VOD, I linked the one that is not working for me...

**VOD / Channel link**
[The url where you encountered the error](https://www.twitch.tv/videos/2128512897)
  
  **Browser**
Chrome (Vivaldi)

**Comment by jindo** [comment]
Can confirm. None of the VODs work anymore.

**Comment by Al-Ghifari8** [comment]
Same here, even after deleting cookies or cache still doesn't work.

**Comment by Endymi0n74** [comment]
still no problem here (edge / firefox)

**Comment by alexroussel** [comment]
Also good for me after upgrading to 0.7.1

**Comment by avase42** [comment]
hi me too same problem on chrome I can no longer watch vod with version 0.7.1

**Comment by KuMaaaaaaaaaaaa** [comment]
> hi me too same problem on chrome I can no longer watch vod with version 0.7.1

I removed and re instaled the 0.7.1 and it seems to work now (i'm on chrome)

**Comment by avase42** [comment]
it's good for also everything works correctly
