### ISSUE TITLE
i tried but it dont work :(

### ISSUE THREAD

**Issue by nakomm** [besuper/TwitchNoSub#105]
**Describe the bug**

**VOD / Channel link**
The url where you encountered the error

**Browser**
Chrome, Edge, Firefox, Brave, ...

**Additional context**

**Comment by nakomm** [comment]
did they just updated so github arent working anymore? i dnt wanna sub to 50channel pls help :(-((

**Comment by canoine** [comment]
> did they just updated so github arent working anymore? 

Perhaps you're right : the 0.6.3 version, which is in the Firefox addons store, doesn't work anymore for me for the last days. But the 0.7.1 version, downloaded here, does work.

**Comment by Januuus** [comment]
I have the same problem on Google Chrome, both 0.63 and 0.7.1 versions are not working anymore. I also tried the last version on Brave and same issue. It sucks, I love this plugin.

**Comment by LordCappuccino** [comment]
It just happened to me in Chrome (124.0.6367.60), but in Firefox it still works.

**Comment by iHaroon29** [comment]
Works on Firefox can confirm.

**Comment by Swihh** [comment]
reinstalled on disk c several times works for me 0.71 chrome

**Comment by stony-berserk** [comment]
was down for me on firefox 125.0.2 but after delete and install of the extension its working. And great job with this project btw.

**Comment by acexae** [comment]
> was down for me on firefox 125.0.2 but after delete and install of the extension its working. And great job with this project btw

did the same on firefox and it worked for me too

**Comment by Resxt** [comment]
It wasn't working for me too so I simply came to the repo and installed it again, without even removing it beforehand. It just updated and after a page refresh it started working again. Firefox btw
Thanks again for this fantastic extension ❤️
