### ISSUE TITLE
0.7.1 dont work

### ISSUE THREAD

**Issue by darthalex2014** [besuper/TwitchNoSub#106]
**Describe the bug**
0.7.1 dont work

**VOD / Channel link**
https://www.twitch.tv/videos/2139961205)](https://www.twitch.tv/videos/2139961205

**Browser**
Chrome 124

**Comment by TheCreeep** [comment]
What country are you in ? Are you on a VPN ?

**Comment by DownHouse** [comment]
Yes, 0.71 does not work.
Use 0.7. It is still working.

**Comment by Minovic921** [comment]
Hey, it ain't working for me, 0.7.1 or 0.7.0, none of them are... Here's a screenshot of the problem.. 
![Screenshot 2024-05-12 074543](https://github.com/besuper/TwitchNoSub/assets/169575803/bf4a9456-8086-4be6-a107-8281507db67d)

**Comment by r3d5ky** [comment]
If the extension doesn't work for you, try installing a userscript manager like tampermonkey and using the [userscript](https://github.com/besuper/TwitchNoSub/raw/master/userscript/twitchnosub.user.js) version of this extension
