### ISSUE TITLE
Service worker registration failed. Status code 2 - "src/background.js"

### ISSUE THREAD

**Issue by Minovic921** [besuper/TwitchNoSub#108]
**Describe the bug**
It just says "Service worker registration failed. Status code 2" then points to "service_worker" : "src/background.js"

**VOD / Channel link**
Every channel I go on, the problem is within the extension menu in Chrome, it points to the error when I install it in the browser's extensions

**Browser**
Google Chrome

**Additional context**
Everytime I download the same error pops up and here's the screenshot
![Screenshot 2024-05-12 074543](https://github.com/besuper/TwitchNoSub/assets/169575803/9d0ec344-61f4-4d9c-9a29-0b18fe36bcfb)

**Comment by besuper** [comment]
Hi, if the extension don't want load you can try to use the [userscript](https://raw.githubusercontent.com/besuper/TwitchNoSub/master/userscript/twitchnosub.user.js)
