### ISSUE TITLE
Not working on Android with Firefox Nightly

### ISSUE THREAD

**Issue by Ultime850** [besuper/TwitchNoSub#109]
Firefox Nightly on Android has an option to load an .xpi addon.
However, once the addon is loaded, it doesn't work, Twitch indicates that you must be subscribed.

**Comment by besuper** [comment]
Hi, the mobile version is not currently supported. You need to load the twitch page on the desktop version for this to work.

**Comment by r3d5ky** [comment]
@Ultime850 there is opensource app for android called Xtra, you can watch streams and sub-only vods with it
Here is a link to it https://github.com/crackededed/Xtra

**Comment by Ultime850** [comment]
> @Ultime850 there is opensource app for android called Xtra, you can watch streams and sub-only vods with it Here is a link to it https://github.com/crackededed/Xtra

Thanks!!!
