### ISSUE TITLE
some vods not working and the chat doesnt popup for me (Mac)

### ISSUE THREAD

**Issue by des255567** [besuper/TwitchNoSub#11]
![Schermata 2022-06-26 alle 16 48 55](https://user-images.githubusercontent.com/108230842/175822794-6a0fe78b-b139-4e36-b0d4-985696409f28.png)

this is the link for that specific vod https://www.twitch.tv/videos/1482377793?filter=archives&sort=time
is there any fix to this , the chat never popups for me and some  vods on that channel always give me that error 
im on mac

**Comment by Troyier** [comment]
Seems to work if you jump forward in the video before the error shows up

**Comment by des255567** [comment]
> Seems to work if you jump forward in the video before the error shows up

Yeah i just tried that and it worked , still cant see the chat replay on the side

**Comment by des255567** [comment]
> For the chat, I forgot to mention it in the readme. It is disabled by default to reduce requests. You can enable it in the extension settings (click on the extension icon)

Oh ok , i just tried to enable it but still nothing pops up

**Comment by besuper** [comment]
This should be fixed with this commit https://github.com/besuper/TwitchNoSub/commit/4fed3d6ea2dbf5750b596dbd72a3a8f3f1dd5c53. Manifest changed, be sure to remove the extension and re-import it to update correctly.

**Comment by des255567** [comment]
it doesnt allow me  me to  re imprt the extension, when i try i get an error on chrome , do you have a link by any cahnce of the extension zip with the updated manifest?

**Comment by des255567** [comment]
> This should be fixed with this commit [4fed3d6](https://github.com/besuper/TwitchNoSub/commit/4fed3d6ea2dbf5750b596dbd72a3a8f3f1dd5c53). Manifest changed, be sure to remove the extension and re-import it to update correctly. (And re-enable chat)

it doesnt allow me me to re imprt the extension, when i try i get an error on chrome , do you have a link by any cahnce of the extension zip with the updated manifest?

**Comment by besuper** [comment]
Click on code 
![image](https://user-images.githubusercontent.com/16976439/176223065-5eb66234-6bb0-4a3c-8c02-9b073a365f16.png)
Then click on Download zip
![image](https://user-images.githubusercontent.com/16976439/176223173-bdde0363-2f2f-44c4-92d4-5b6460ccea4c.png)

When it's done uncompress the zip. Now you can re-import the extension with the uncompressed folder. If there is still an error send it to me.
