### ISSUE TITLE
Plugin no longer permits viewing of sub-only vods 

### ISSUE THREAD

**Issue by ARival** [besuper/TwitchNoSub#118]
Plugin no longer permits viewing of sub-only VODs.

https://www.twitch.tv/videos/2186916601?filter=archives&sort=time

Firefox MacOS Sonoma 14.0

![image](https://github.com/besuper/TwitchNoSub/assets/5307339/3d0dcc24-8bd3-4ca2-8170-3f16f224e8e7)

**Comment by DavidGamer981** [comment]
+1. 
Same problem.

**Comment by bodnar07** [comment]
Same. Chrome: 126.0.6478.127

**Comment by ten4dinosaur** [comment]
![image](https://github.com/user-attachments/assets/4232f9d8-4622-4984-b7da-4f538858fefc)
Try incognito

**Comment by xLamday** [comment]
Hello guys, i kinda figured it out on how to make it work again.

Try simply removing the extension and re-install it.

I did this simple step and it started working again.

Cheers!

**Comment by DavidGamer981** [comment]
> Hello guys, i kinda figured it out on how to make it work again.
> 
> Try simply removing the extension and re-install it.
> 
> I did this simple step and it started working again.
> 
> Cheers!

Yes, it works for me now as you said. Thank you so much!! 👍

**Comment by trekshcool** [comment]
Yup reinstall still works.
