### ISSUE TITLE
Firefox Compatibility?

### ISSUE THREAD

**Issue by Cydver** [besuper/TwitchNoSub#12]
Hi there, thanks so much for developing this incredibly useful tool! Really helps especially when the streamer says he only makes VODs sub-only to avoid DMCA issues :)

Just wondering: Are you planning on creating a version for Firefox in the near future?

**Comment by besuper** [comment]
Sure but I think firefox doesn't fully support manifest v3. I need to wait to implement it.

**Comment by besuper** [comment]
I will temporarily use 2 different manifests to support firefox. You can now download the firefox version from releases.

**Comment by Cydver** [comment]
Wow thank you so much! Really appreciate you doing this!
