### ISSUE TITLE
BUG 0.7.1

### ISSUE THREAD

**Issue by keilogic** [besuper/TwitchNoSub#128]
**Describe the bug**
infinite loading 

**VOD / Channel link**
every stream / https://www.twitch.tv/xqc

**Browser**
Chrome

**Additional context**

**Comment by RomainSem** [comment]
Same issue in Firefox

**Comment by louis-mps** [comment]
Duplicate #127

**Comment by besuper** [comment]
Should be fixed in version 0.8
