### ISSUE TITLE
Version 0.7.1 not working.

### ISSUE THREAD

**Issue by darkmatterdavson** [besuper/TwitchNoSub#129]
**Describe the bug**
I have stuck loading icon in player(VOD/Livestream).

**VOD / Channel link**
Any livestream on twitch

**Browser**
Firefox

**Additional context**
Attached pictures

Example livestream: (Stuck in loading screen)
![obrazek](https://github.com/user-attachments/assets/dd39fe98-a469-47c1-81b4-700018d70cc4)
Error message:
![obrazek](https://github.com/user-attachments/assets/a17e250f-a882-46d1-9d50-72bf8729149d)

**Comment by Hir92643fdsx3axss** [comment]
Same for Google Chrome 0.7.1 seems not to be working again. Also stuck at the loading icon in player(VOD/Livestream).

**Comment by louis-mps** [comment]
Duplicate #127

**Comment by besuper** [comment]
Should be fixed in version 0.8
