### ISSUE TITLE
does not work in this channel

### ISSUE THREAD

**Issue by rkly8766** [besuper/TwitchNoSub#15]
https://www.twitch.tv/murderofbirds
ex. video (https://www.twitch.tv/videos/1497421933?filter=highlights&sort=time)

**Comment by besuper** [comment]
Hi, do you use Firefox or another browser?

**Comment by rkly8766** [comment]
i use google chrome

**Comment by besuper** [comment]
Try to download the extension with the Code button 
![image](https://user-images.githubusercontent.com/16976439/179098430-4153cb73-d8eb-4c17-b48c-35806f5f1578.png)
And reinstall the extension, it should work

**Comment by rkly8766** [comment]
thanks so much it works now!!
