### ISSUE TITLE
VOD stops loading after a while

### ISSUE THREAD

**Issue by lmu08** [besuper/TwitchNoSub#19]
Hi, thanks for making this extension!

I noticed something a bit weird. At first everything works great, the VOD is loading fine; but if I skip around too much, eventually the player just stops loading it. Then it keeps buffering regardless of what timestamp I select... And if I reload the page after that, the VOD doesn't even load at all. (just getting a black screen, and the player is buffering)

I don't know much about it, but I tried looking in the Chrome network tab, and it looks like Cloudfront just stops responding...

![image](https://user-images.githubusercontent.com/28020294/179396871-f631b814-2359-46c5-9edc-9267bffb20af.png)

I thought this could be a limitation on their end, but if I paste the same *.m3u8 link in my adress bar, the file downloads just fine...

For reference I am using Chrome 103 on Windows 10.

Thanks in advance for your help!

**Comment by besuper** [comment]
Hi, this bug maybe has come from the plyr player. I switched to videojs in the last commit. Try to update the extension with the code on the master branch
Let me know if it happens again

**Comment by lmu08** [comment]
Hi, thanks for the help;
I updated the extension, but it looks like the bug is still here :(
At least this player gives an error, unlike the previous one:
![image](https://user-images.githubusercontent.com/28020294/184708422-3bf01f83-df77-4db2-96b4-219030c31878.png)
Were you able to reproduce the bug on your side? 
What I did is basically keep skipping the VOD to random points (both forward and back), for about a minute, until the player stops loading. So really the same issue as before.
Let me know if you need more info!

**Comment by besuper** [comment]
I tried to reproduce the bug but it didn't happen to me. Maybe it's related to the VOD? Do you have this issue on all VODs?
