### ISSUE TITLE
not working on edge 

### ISSUE THREAD

**Issue by M1sterCodex** [besuper/TwitchNoSub#22]
just unpaked it and it's not working idk

**Comment by besuper** [comment]
Hi, I just tested the extension on edge and everything was working. Do you have any errors in the console or in the extension manager?

**Comment by HerIsDia** [comment]
Hi, I can confirm for me than the extension works on edge.

**Comment by besuper** [comment]
This issue may be related to the muted segment issue (https://github.com/besuper/TwitchNoSub/issues/23)



> just unpaked it and it's not working idk

Can you send me the VOD link please

**Comment by M1sterCodex** [comment]
hello sorry for the late replay the vod was deleted the day after but twitch was still showing it,
I tested again with another vod from a different twitch channel and it works!! thx !!

also works on brave browser
