### ISSUE TITLE
VODs black screen

### ISSUE THREAD

**Issue by almtst** [besuper/TwitchNoSub#25]
It seems that VODs manually made only for subs are not working properly on version 0.5.1, they get stuck on a black screen, but work just fine using version 0.3, this one for example https://www.twitch.tv/videos/1573620528, tested on Firefox and Edge with the same result.

**Comment by besuper** [comment]
Fixed here https://github.com/besuper/TwitchNoSub/commit/6f14f0d5685f58bbd38b4da712477b910a891593
