### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by bolbolfolfol** [besuper/TwitchNoSub#28]
Hi
thx for this wonderful (?) extention ^......^

i got an error on installation :
https://imgur.com/a/VXAlXN1

can yo please make a normal CRX file ?

**Comment by besuper** [comment]
Hi, I don't know what this error is maybe try downloading the extension from the master branch. Remove the extension and retry with a fresh install

**Comment by bolbolfolfol** [comment]
> 

i used an old build of Chromium
i updated now and it worked
thank you so much and i hope you keep it working ^........^ !
