### ISSUE TITLE
Playback cannot continue. No available working or supported playlists.

### ISSUE THREAD

**Issue by TristanUPPA** [besuper/TwitchNoSub#31]
I got this error "Playback cannot continue. No available working or supported playlists." on some VOD

![image](https://user-images.githubusercontent.com/90894382/189340955-05e9ae6c-068c-4f3d-b860-2c0f9e79b3cb.png)

**Comment by besuper** [comment]
Hi, this is related to https://github.com/besuper/TwitchNoSub/issues/23

**Comment by besuper** [comment]
This issue should be fixed with version 0.6
