### ISSUE TITLE
User Script ?

### ISSUE THREAD

**Issue by vic60400** [besuper/TwitchNoSub#32]
Hi

Any userscript version planned ?

**Comment by besuper** [comment]
Hi, I will see if it's possible

**Comment by sn-o-w** [comment]
@besuper I would also like to have a user script. It would be even easier to get updates this way.

**Comment by vic60400** [comment]
I found better ;) 

https://chrome.google.com/webstore/detail/twitchnosub/agoolijpgfbcenckfnjcpkccfcnomifg

**Comment by besuper** [comment]
Hi, after a long time it's [available](https://raw.githubusercontent.com/besuper/TwitchNoSub/master/userscript/twitchnosub.user.js) :)
