### ISSUE TITLE
Pressing left reloads the page

### ISSUE THREAD

**Issue by FirestarJT07** [besuper/TwitchNoSub#34]
I was using latest version and i wanted to go backwards on a vod and when pressing left arrow the page reloads, why this happens?

**Comment by Tom-077** [comment]
Hi, i had the same issue.
To fix this, i commented the line 42 in the App.js : location.reload()
I didn't notice any bad side effect of this change, even if this line is intended to "prevent VOD to load twice" but there's surely a proper way to fix this.

**Comment by besuper** [comment]
Hi, this is now fixed in 0.6!
