### ISSUE TITLE
[Firefox] No chat replay when connected with account

### ISSUE THREAD

**Issue by YofarDev** [besuper/TwitchNoSub#35]
The chat replay option doesn't work on firefox when I'm signed in, but works when I'm not. I've tried on a profile with no other extensions. and I was not banned from the channel. Everything works on chrome.

In the logs of the console, `TypeError: messages.comments is undefined` is looping

(I'm on linux I don't know if it's matter)

**Comment by NicotherZ** [comment]
+1
Same problem, hope you'll can fix it please, your addon is amazing !!

**Comment by besuper** [comment]
Hi, the chat is fixed in version 0.6 for firefox

**Comment by NicotherZ** [comment]
Great, you have fixed studio mode too ! Wow Perfect Addon now !! THANKS !
