### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by mercury6699** [besuper/TwitchNoSub#37]
It doesn't work ((

**Comment by bibaryskoutepov** [comment]
Any tips, Sir?

**Comment by embyveddii** [comment]
doesnt work for me either. im on firefox

**Comment by embyveddii** [comment]
it just doesn't work. like nothing changes. I still can't watch the VODs. It's identical to without the extension

**Comment by Endymi0n74** [comment]
can you try another browser?

**Comment by Lukyzzz** [comment]
Same here, it seems to work on Chrome (Win) but not on mobile, at least on the extension that I used on the past (Kiwi , Which it worked on the past), if anyone know any Browser that support this on mobile and let me know, I appreciate it.

**Comment by besuper** [comment]
Hi, can you add more details please (a screen of the player and the console logs) thanks!

**Comment by Lukyzzz** [comment]
Seems version 3.0 kinda works

**Comment by besuper** [comment]
The latest version should now work
