### ISSUE TITLE
Any recommendations for mobile ?

### ISSUE THREAD

**Issue by Lukyzzz** [besuper/TwitchNoSub#38]
Any recommendations for mobile browsers that work with this ?
Used Kiwi on the past but it doesn't seems to work anymore.

**Comment by besuper** [comment]
Hi, can you try version 0.6 please? It could work on mobile

**Comment by FlameWasTaken** [comment]
> Hi, can you try version 0.6 please? It could work on mobile

Doesn't work on Kiwi
![Screenshot_20230105-233553](https://user-images.githubusercontent.com/71017503/210900511-bf8933d6-5070-490e-8daa-02023eca79d5.png)
