### ISSUE TITLE
added quality options

### ISSUE THREAD

**Issue by yankeesback** [besuper/TwitchNoSub#4]
thank you for your great work, i've added video quality options using "videojs-quality-selector" plugin, the modified extension can be found on my profile, 
regards.

**Comment by besuper** [comment]
This is an interesting feature, I could add it when I have time. But if you know how it works you could make a pull request if you want to contribute.

**Comment by yankeesback** [comment]
> 

hi, some modifications in app.js:

 const fullUrl = domain + "/360p30/index-dvr.m3u8";
	const fullUrl480 = domain + "/480p30/index-dvr.m3u8";
	const fullUrl720 = domain + "/720p60/index-dvr.m3u8";
	const fullUrlsource = domain + "/chunked/index-dvr.m3u8";
	const fullUrl160 = domain + "/160p30/index-dvr.m3u8";

 checkUrl(fullUrl).then((_, statut) => {
        if (statut === "success") {
            // Insert the new player
            contentStream.html(
 `<div data-setup="{}" preload="auto" class="video-js vjs-16-9 vjs-big-play-centered vjs-controls-enabled vjs-workinghover vjs-v7 player-dimensions vjs-has-started vjs-paused vjs-user-inactive ${className}" id="player" tabindex="-1" lang="en" role="region" aria-label="Video Player">
                    <video id="video" class="vjs-tech vjs-matrix" controls>
						<source src="${fullUrlsource}" type="application/x-mpegURL" id="vod4" res="source" label="source" selected="true">
						<source src="${fullUrl720}" type="application/x-mpegURL" id="vod3" res="720" label="720p60">
						<source src="${fullUrl480}" type="application/x-mpegURL" id="vod2" res="480" label="480p">
						<source src="${fullUrl}" type="application/x-mpegURL" id="vod" res="360" label="360p">
						<source src="${fullUrl160}" type="application/x-mpegURL" id="vod0" res="160" label="160p">
                    </video>
                </div>`

then under playback speed function i've added this :
//Add quality selector
			videojs('video', {}, function() {
			var player = this;
			player.controlBar.addChild('QualitySelector');
			});


and of course i included the plugin js files in \src\scripts :
selector.js
silvermine-videojs-quality-selector.min.js

and the css file in src\style : 
quality-selector.css

and on the manifest file....

**Comment by besuper** [comment]
Thanks for the help! It's now added (https://github.com/besuper/TwitchNoSub/commit/39240c721931028ab38f05b5f2d918a88f4f00f6)
