### ISSUE TITLE
Playback cannot continue....

### ISSUE THREAD

**Issue by fighellboy** [besuper/TwitchNoSub#40]
Hello,
this happens every time when i try play any sub-only video on twitch. Extension worked in older versions without this issue. I use Edge browser. I currently use version of extension 0.3 and there is no problem with that. Anyway, really thanks for this extension 👌😊

![image](https://user-images.githubusercontent.com/64019702/199029986-6a7e60b8-cf75-4fde-a596-e38dee3bbf91.png)
![image](https://user-images.githubusercontent.com/64019702/199030341-574c3b91-d87e-45f7-a577-d95d455790ce.png)

**Comment by HornWilly** [comment]
I think this is related to https://github.com/besuper/TwitchNoSub/issues/23

**Comment by besuper** [comment]
This is fixed in latest version
