### ISSUE TITLE
error message on some vods

### ISSUE THREAD

**Issue by epogle** [besuper/TwitchNoSub#44]
Hello, 
On some specific vods I get this error message "Playback cannot continue. No available working or supported playlists."
like for this vod https://www.twitch.tv/videos/1648015995
![Untitled](https://user-images.githubusercontent.com/102364350/201200593-641d073a-daf2-4ff8-8f2c-bab0d462dfc9.png)

**Comment by krivbas1** [comment]
I am getting the same error
It is sporadic, yet very frustrating
I am not complaining but I am a lil' bit
Thanks for all you work Be

**Comment by besuper** [comment]
Hi, can you test with version 0.6 please

**Comment by krivbas1** [comment]
Now I am getting a different error on same vods with .6
"There was a network error.  Error 2000"
This is only happening on same vods as before, like this one:
https://www.twitch.tv/videos/1650234179

**Comment by besuper** [comment]
hey, it's now fixed in 0.6.1

**Comment by krivbas1** [comment]
it is fixed  thank you
