### ISSUE TITLE
Progress bar on VODs longer than actual full VOD time

### ISSUE THREAD

**Issue by Thebessemer** [besuper/TwitchNoSub#45]
Sometimes when I open a VOD the progress bar is longer than the time of the VOD itself. For example if the VOD is 2 hours long, it only takes up about a quarter of the progress bar and the rest is just hours of dead time, which makes it very difficult to skip to specific timestamps and such. I'm not sure why it's happening

**Comment by besuper** [comment]
Hi, can you test with version 0.6 please

**Comment by Thebessemer** [comment]
Works much better now, appreciate all your hard work

**Comment by Thebessemer** [comment]
👍
