### ISSUE TITLE
0.6.1 Not Working. Uncaught Type Error.

### ISSUE THREAD

**Issue by SabreRunner** [besuper/TwitchNoSub#52]
Uncaught TypeError: Cannot read properties of undefined (reading 'local')
### Context
src/background.js
### Stack Trace
src/background.js:6 (anonymous function)

`// Make background wake up
chrome.webNavigation.onBeforeNavigate.addListener(function () {

}, {
    url: [{ hostContains: "twitch" }]
});

var isChrome = chrome.declarativeNetRequest != undefined;

// Patching amazon service worker (75a2c99f45ecb5aa3225)
if (isChrome) {
    // declarativeNetRequest only available on chrome
    chrome.declarativeNetRequest.updateDynamicRules({
        addRules: [{
            'id': 1001,
            'priority': 1,
            'action': {
                'type': 'redirect',
                'redirect': {
                    url: chrome.runtime.getURL("src/patched-amazon.js")
                }
            },
            'condition': {
                'urlFilter': 'https://static.twitchcdn.net/assets/amazon-ivs-wasmworker.min-*.js',
            }
        }],
        removeRuleIds: [1001]
    })
} else {
    // Support firefox here
    browser.webRequest.onBeforeRequest.addListener(
        function (details) {
            return { redirectUrl: browser.runtime.getURL("src/patched-amazon.js") };
        },
        {
            urls: [
                "https://static.twitchcdn.net/assets/amazon-ivs-wasmworker.min-*.js"
            ],
            types: ["main_frame", "script"]
        },
        ["blocking"]
    );
}`

Google Chrome
Chrome is up to date
Version 108.0.5359.95 (Official Build) (64-bit)

**Comment by besuper** [comment]
Is the issue still there after reinstalling the extension?

**Comment by reisei1** [comment]
0.6.2 also not working on Firefox. streams and clips won't play

**Comment by Endymi0n74** [comment]
worked before, still working now on firefox 110.0a1 nightly without error

**Comment by Kuddus73** [comment]
@besuper The Uncaught TypeError occurs when the extracted folder of the extension is deleted or moved from its initial location after installing it.
This bug is still present in v0.6.3.

Since keeping the extracted folder is useless after the installation, could you fix this issue?

**Comment by besuper** [comment]
If not working try the [userscript](https://raw.githubusercontent.com/besuper/TwitchNoSub/master/userscript/twitchnosub.user.js)
