### ISSUE TITLE
Store ?

### ISSUE THREAD

**Issue by AudricSan** [besuper/TwitchNoSub#53]
I wonder if you were going to publish them on the store?

**Comment by ashishkotnala29** [comment]
This extension clearly violates ToS of twitch and moreover directly hurts the revenue of the company as well as the content creators. There's now way this extension is getting approved to any store. Even if it does it can easily be taken down by DMCA. It's not even safe to host the code here.
Twitch/Amazon can do a DMCA takedown any day.

**Comment by AudricSan** [comment]
Hoo okay i understand ! 
Thanks for your answerd
