### ISSUE TITLE
Not working any more

### ISSUE THREAD

**Issue by JCGodart** [besuper/TwitchNoSub#54]
TwitchNoSub used to work fine for me (FF / Ubuntu). But the Twitch update seems to prevent watching (video & sound) even in live, whereas the chat is still ok.

Edit : as suggested, version 0.5.1 is working fine. Thanks

**Comment by Maxoumi** [comment]
same

**Comment by Endymi0n74** [comment]
works like a charm on firefox for me

**Comment by Endymi0n74** [comment]
disabled : "only for sub"
![image](https://user-images.githubusercontent.com/102302606/211655853-97705d5f-bf7c-4e41-a80d-0dfcf8aba80d.png)
enabled : video ok
![image](https://user-images.githubusercontent.com/102302606/211655607-fa0c7cf7-7412-4dd2-9fa3-7cde8a357d55.png)

**Comment by Maxoumi** [comment]
Doesn't work on firefox for me. It was working fine 1/2 hour ago then suddenly nothing worked anymore

**Comment by Endymi0n74** [comment]
> Doesn't work on firefox for me. It was working fine 1/2 hour ago then suddenly nothing worked anymore
> 
> EDIT : I just tested with version 5.1 and it works

i'm using latest

**Comment by reisei1** [comment]
latest release stopped working on Firefox yesterday. streams and even clips won't start playing. as someone mentioned before version 0.5.1 still works so a downgrade seems like the best solution for now

**Comment by Striffly** [comment]
For Chrome / Chromium, `git clone` the master branch, a patch was released two hours ago and makes the extension functional again

**Comment by Maxoumi** [comment]
> For Chrome / Chromium, `git clone` the master branch, a patch was released two hours ago and makes the extension functional again

Work perfectly thanks

**Comment by besuper** [comment]
Can someone confirm if its fixed with latest amazon worker (1.14.0)?

**Comment by JCGodart** [comment]
> Can someone confirm if its fixed with latest amazon worker (1.14.0)?

As suggested, version 0.5.1 is working fine for me (Fire Fox / Ubuntu). I wouldn't call it "fixed", but at least it's a workaround.

**Comment by besuper** [comment]
> > Can someone confirm if its fixed with latest amazon worker (1.14.0)?
> 
> As suggested, version 0.5.1 is working fine for me (Fire Fox / Ubuntu). I wouldn't call it "fixed", but at least it's a workaround.

I know but I need confirmation for chrome / chromium so I can make a release for firefox. On my side it works but I prefer to have a feedback before publishing a release

**Comment by Maxoumi** [comment]
I'm on chrome. It no longer worked, but after the fix 14 hours ago it works perfectly again(See my message above, I was with chrome)

**Comment by ManneN1** [comment]
> > > Can someone confirm if its fixed with latest amazon worker (1.14.0)?
> > 
> > 
> > As suggested, version 0.5.1 is working fine for me (Fire Fox / Ubuntu). I wouldn't call it "fixed", but at least it's a workaround.
> 
> I know but I need confirmation for chrome / chromium so I can make a release for firefox. On my side it works but I prefer to have a feedback before publishing a release

The latest update released yesterday works in Opera (Chromium). Thanks for the quick fix.

**Comment by ashishkotnala29** [comment]
0.6.2 works!

**Comment by JCGodart** [comment]
0.6.2 works for me (FireFox / Ubuntu). Thanks for the quick fix
