### ISSUE TITLE
It got patched , infinte loading screen on vods and normal streams don't load unless i disable it

### ISSUE THREAD

**Issue by Zamz00m** [besuper/TwitchNoSub#56]

**Comment by C6ix** [comment]
Yep, same

**Comment by f5012010** [comment]
By chance, I have tried version 0.2 in Microsoft Edge and it works for me.

**Comment by f5012010** [comment]
0.6.1 also works.

**Comment by micromancerr** [comment]
now it works in popout window only

**Comment by ashishkotnala29** [comment]
Working fine on chrome with 0.6.2.

Thanks for your work @besuper

**Comment by Zamz00m** [comment]
It works now with latest release , thank you for your work , appreciate it. @besuper
