### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by MalcolmBrt** [besuper/TwitchNoSub#57]
Hello, I don't know much about javascript but this line in amazon-ivs-worker.min.js seems weird, what does it do?

![image](https://user-images.githubusercontent.com/119721410/212588845-1531bcac-f15b-4e83-97bb-3861f64b0b8c.png)

**Comment by besuper** [comment]
Hello, it's the latest version of the amazon ivs player (https://aws.amazon.com/ivs/). Twitch use this player on their website. If you go here https://docs.aws.amazon.com/ivs/latest/userguide/player-videojs.html you will see a link in the setup that return the same code
