### ISSUE TITLE
Error on Firefox

### ISSUE THREAD

**Issue by Randomire44** [besuper/TwitchNoSub#58]
Hey, I got this error on Firefox sometimes when I start twitch on a stream, clip, or VOD, which makes the stream black screen and I need to refresh the page to make it work. It doesn't happen everytime.

"Loading the script at "https://raw.githubusercontent.com/besuper/TwitchNoSub/master/src/amazon-ivs-worker.min.js" with importScripts() was blocked due to a forbidden MIME type ("text/plain")."

**Comment by ashishkotnala29** [comment]
Are you updated to v0.6.2?

**Comment by Randomire44** [comment]
Yes I have the 0.6.2 version.

**Comment by Rex000** [comment]
I have the same issue. It seems like it started happening after the recent firefox update.

**Comment by leonid-dalin** [comment]
Firefox user here on 0.6.2;

I thought I had a similar issue, but after approximate 8 minutes of just waiting the VOD started.

**Comment by leonid-dalin** [comment]
Firefox user here on 0.6.2;

Same issue as OP. 
![image](https://user-images.githubusercontent.com/57640182/213375859-9e920292-c83e-444d-80e9-e7a848810f65.png)

**Comment by Rex000** [comment]
> 

I did, but still the same thing. Whether it's live streams or vods they keep loading.

**Comment by Rex000** [comment]
> > Hey, I got this error on Firefox sometimes when I start twitch on a stream, clip, or VOD, which makes the stream black screen and I need to refresh the page to make it work. It doesn't happen everytime.
> > "Loading the script at "https://raw.githubusercontent.com/besuper/TwitchNoSub/master/src/amazon-ivs-worker.min.js" with importScripts() was blocked due to a forbidden MIME type ("text/plain")."
> 
> Have you tried to reinstall the extension completely?

I did, but still the same thing. Whether it's live streams or vods they keep loading.

**Comment by Randomire44** [comment]
> > Hey, I got this error on Firefox sometimes when I start twitch on a stream, clip, or VOD, which makes the stream black screen and I need to refresh the page to make it work. It doesn't happen everytime.
> > "Loading the script at "https://raw.githubusercontent.com/besuper/TwitchNoSub/master/src/amazon-ivs-worker.min.js" with importScripts() was blocked due to a forbidden MIME type ("text/plain")."
> 
> Have you tried to reinstall the extension completely?

I tried reinstalling today and I still sometime have the infinite loading and this error in the console

**Comment by reisei1** [comment]
try pressing ctrl+F5 to do a hard reload. that worked for me and now all streams load 1st try and even faster than before. currently using Firefox 109.0

**Comment by Randomire44** [comment]
> try pressing ctrl+F5 to do a hard reload. that worked for me and now all streams load 1st try and even faster than before. currently using Firefox 109.0

It seems to work when you got the bug but if you close the tab and reopen twitch it will still do the bug

**Comment by Dooleh** [comment]
Didn't think it was necessary to add to this, but since it not getting fixed, it's still broken on updated firefox - black infinite loading screen. The right click reload, or ctrl + F5 just temporarily fixes it.

**Comment by Rex000** [comment]
Don't know why this temporary "fix" was even suggested. Just doing ctrl+F5 doesn't fix or modify any code.

**Comment by Dooleh** [comment]
It makes the videos play for me, therefore works. Without it, they are always stuck on an infinite load.

**Comment by besuper** [comment]
The issue should be fixed with 0.6.3
