### ISSUE TITLE
Uploaded Vods takes too long loading and when it loads, it plays a small amount and gets back to loading again

### ISSUE THREAD

**Issue by Zamz00m** [besuper/TwitchNoSub#61]
i don't know if it's an issue of the extension or my browser (brave) but i thought it worth mentioning , thanks in advance.

**Comment by besuper** [comment]
Hi, does this problem occur all the time? Have you tried with another browser?

**Comment by Zamz00m** [comment]
HI, yes,  it does happen all the time with the uploaded (not streamed) vods, and to answer the sec question , i tried google chrome and it still does happen but to be fair both are based on chromuim so i don't know... maybe the firefox xpi file work but i can't be sure cuz i don't have it.

**Comment by Zamz00m** [comment]
to understand the problem better ,the vod buffers alot like i don't have an good internet connection which i checked funny enough.
