### ISSUE TITLE
Error #2000

### ISSUE THREAD

**Issue by KaliC4li** [besuper/TwitchNoSub#63]
Im having "There was a network error. Please try again. (Error #2000)" after just one watch
![image](https://user-images.githubusercontent.com/125854386/220234710-1cc664ae-0e27-4f4e-836c-482c36c8fadb.png)

**Comment by besuper** [comment]
Hi, do you have this issue on other VODs? Can you send me send VOD link

**Comment by adelkk** [comment]
I am having the same error on every VOD

**Comment by mfb106** [comment]
I also am having the same error on all the locked (from sub only content) VODs I have checked.

**Comment by KaliC4li** [comment]
i also have this in other vods even the non-sub only mode

**Comment by KaliC4li** [comment]
It fixed itself after 2 days, ill inform you if it happens again
