### ISSUE TITLE
0.6.3 suddently don't work anymore

### ISSUE THREAD

**Issue by este9** [besuper/TwitchNoSub#64]
It was perfectly working for one month but now I get some error.

**Comment by Asotikk** [comment]
same for me i get the error code on firefox and opera

**Comment by RichardHelp** [comment]
Here too stopped

**Comment by este9** [comment]
I think its twitch

**Comment by Zamz00m** [comment]
same with me , i use brave browser

**Comment by besuper** [comment]
Hi, brave is fixed https://github.com/besuper/TwitchNoSub/commit/601a23b66c87853b5340e4dca91007cc8b3036a2
