### ISSUE TITLE
Stopped working (version 0.6.3)  started working again

### ISSUE THREAD

**Issue by RichardHelp** [besuper/TwitchNoSub#65]
I used version 0.6.3 a few weeks ago, and out of nowhere, today it stopped working

**Comment by Bsile** [comment]
same issue, giving me error 2000

**Comment by RichardHelp** [comment]
> same issue, giving me error 2000
Yeah, mine is also showing the same error. I believe they will fix it soon.

**Comment by Maxoumi** [comment]
same here on chrome

**Comment by RichardHelp** [comment]
> same here on chrome

started working again
