### ISSUE TITLE
Different error today (version 0.6.3)

### ISSUE THREAD

**Issue by RichardHelp** [besuper/TwitchNoSub#67]
A few weeks ago it had stopped working, but it came back on the same day. Today it is still working, but every 3 minutes (more or less), the vod crashes, then I wait about 30 seconds, it comes back, a few minutes pass and it crashes again. I don't think it's my internet because it started dropping tonight. Comment if you have the same error as mine, or if it's just for me. By the way, today about 40 minutes ago I got this error: Error #5000 but I was able to fix this. If you stop with this "error", I'll let you know in the comments

**Comment by Zamz00m** [comment]
same for me

**Comment by ilvro** [comment]
vods dont load at all for me
