### ISSUE TITLE
Reinstalled and fixed issue (VOD'S not loading on firefox)

### ISSUE THREAD

**Issue by D3ADHUNT3RS** [besuper/TwitchNoSub#69]
On firefox VOD'S are loading indefinitely. Did twitch fixed it?

**Comment by D3ADHUNT3RS** [comment]
Working fine on Brave

**Comment by Owl220** [comment]
I have the same issue on firefox :(

**Comment by besuper** [comment]
Hi, it's working on my side. Can you send me a VOD link please

**Comment by leochras** [comment]
Can confirm with this clip: https://www.twitch.tv/videos/1782596705
