### ISSUE TITLE
Black screen on all sub vods

### ISSUE THREAD

**Issue by Troyier** [besuper/TwitchNoSub#7]
When trying to play a sub video the player doesnt load and there is only a black screen
![image](https://user-images.githubusercontent.com/107682380/174278497-7417d854-1a31-4f2d-8190-2570a087ae12.png)

**Comment by besuper** [comment]
Should be fixed here https://github.com/besuper/TwitchNoSub/commit/d9a8d58de898607659565bb3b78ef29e9a3acd74

**Comment by Troyier** [comment]
Yup it has been fixed.Thanks
