### ISSUE TITLE
No longer working (Chrome)

### ISSUE THREAD

**Issue by ShesAaRebel** [besuper/TwitchNoSub#70]
When I try to watch a VOD, the video area will flash (saying you need to be subscribed), and then a blank screen with a purple question mark appears.
I've read a comment somewhere else saying that they think Amazon/Twitch just did a new patch, and have caught on to this.
I'm not sure if the creator is aware or not, and is working on a solution...?

If anyone is still able to use this fine with another browser, let me know!
It was good while it lasted at least.

**Comment by Ashesh3** [comment]
It works fine for me as of today, using on Edge Version 111.0.1661.54

**Comment by besuper** [comment]
Hi, it's working on my side. Can you send me a VOD link please
