### ISSUE TITLE
The extension don't want to work on Brave

### ISSUE THREAD

**Issue by Galipiaf** [besuper/TwitchNoSub#73]
Hi, 
I'm using brave and when I decide to download the latest version, I got an error and this message. I try with the 0.6.2 and I still have that error. Do you know what I can do for not having it anymore? 
Thanks

![Screenshot_2](https://user-images.githubusercontent.com/131800633/234344060-4074f882-0f80-4eef-9063-ce2a367c4d05.png)

**Comment by besuper** [comment]
Hi, you can try the [userscript](https://raw.githubusercontent.com/besuper/TwitchNoSub/master/userscript/twitchnosub.user.js) if the extension is not working
