### ISSUE TITLE
[Suggestion] Support player.twitch.tv by default

### ISSUE THREAD

**Issue by 4164696f73** [besuper/TwitchNoSub#78]
In manifest.json, add "https://player.twitch.tv/*"
```
    "host_permissions": [
        "https://www.twitch.tv/*",
        "https://player.twitch.tv/*",
        "https://static.twitchcdn.net/assets/*"
    ],
```

Checked in my own browser (Brave), works flawlessly. This definitely is not needed, but is a nice touch, so that you don't have to press the extension.

Disclaimer: If you encounter this not working, it's not that this line does not work, but the extension itself sometimes fails to do its job. I tested it extensively, and sometimes it works, sometimes it does not. Not a big deal because the extension is still flagged as "work in progress". :)

**Comment by NewbieH4x** [comment]
Can you tell why is this needed? I've been using the extension as-is fine on Chrome without issues.

Also if it's really needed then why add multiple subdomains and not whitelist `https://*.twitch.tv/*` instead?

**Comment by 4164696f73** [comment]
As I said, it's **definitely not needed**. I personally watch everything in "pop-up" mode, including vods, and this extension does not support the pop-up player right now - you have to activate the extension by-hand to make it work.

Pop-up player is generally faster and has less issues as it does not have to load the whole Twitch website.

**Comment by besuper** [comment]
Hi, sorry for the long wait, it's added! https://github.com/besuper/TwitchNoSub/commit/7cddc2735ece48b607af250a36074de165e6a1d7
