### ISSUE TITLE
TwitchNoSub needs reload at every restart of my browser

### ISSUE THREAD

**Issue by rylaz** [besuper/TwitchNoSub#81]
**Describe the bug**
The VOD unblocker won't work for me at every start of my browser, I need to refresh it every time.

**Error** : Same error as if you don't have the unblocker; This video is only available to subscribers. Sub now to watch and support *******.

**Browser**
Brave

Thanks for help!

**Comment by besuper** [comment]
Hi, unfortunately it's a brave issue https://github.com/besuper/TwitchNoSub/issues/82

**Comment by Sp0kzz** [comment]
Add the following code to the top of src/background.js:

const reloadExtension = () => {
chrome.runtime.reload();
};
chrome.runtime.onStartup.addListener(() => {
// Reload the extension when the browser starts
reloadExtension();
});

**Comment by besuper** [comment]
Hi, this is fixed in https://github.com/besuper/TwitchNoSub/commit/601a23b66c87853b5340e4dca91007cc8b3036a2. thanks!
