### ISSUE TITLE
Doesnt work on brave

### ISSUE THREAD

**Issue by M3tR3mix** [besuper/TwitchNoSub#82]
literally not working tried all the versions, it works when you install for the first time but if you close brave and open it again it wont work unless you disable and renable the extension everytime, sometimes i get a message that says vod is for sub only, sometimes the same error but the message is barred and says just kidding watch vod but it doesnt work when clicking. 

literally every channel or vod i have tried so doesnt matter i think

Brave
![Error](https://github.com/besuper/TwitchNoSub/assets/119697761/dea26a1f-0aa6-45fd-ac20-4c766235e797)

**Comment by JannesDev** [comment]
I'm on Brave and it works perfectly fine for me.

**Comment by lheintzmann1** [comment]
It also doesn't work for me on Brave

**Comment by 4164696f73** [comment]
For me, it works as long as you load it unpacked. Don't use .crx, just use the source, and you have to refresh the extension every time you open Brave. This is a little annoying, but it actually does work fine.

**Comment by besuper** [comment]
Hi, unfortunately it's a brave issue https://github.com/brave/brave-browser/issues/30854

**Comment by Sp0kzz** [comment]
I faced the same issue, and doing this fixed it for me. Add the following code to the top of src/background.js:

const reloadExtension = () => {
  chrome.runtime.reload();
};
chrome.runtime.onStartup.addListener(() => {
  // Reload the extension when the browser starts
  reloadExtension();
});

**Comment by M3tR3mix** [comment]
> I faced the same issue, and doing this fixed it for me. Add the following code to the top of src/background.js:
> 
> const reloadExtension = () => { chrome.runtime.reload(); }; chrome.runtime.onStartup.addListener(() => { // Reload the extension when the browser starts reloadExtension(); });

this solved the issue thanks
