### ISSUE TITLE
No Background sound

### ISSUE THREAD

**Issue by dextisol** [besuper/TwitchNoSub#85]
**Describe the bug**
I watched throught the VOD and i couldn't hear any sounds besides the streamer

**VOD / Channel link**
(https://www.twitch.tv/videos/1944939265)

**Browser**
Chrome, Brave, Firefox

**Additional context**
There was no background sounds (besides the streamer), no music

**Comment by Endymi0n74** [comment]
works here

**Comment by dextisol** [comment]
How?

**Comment by Endymi0n74** [comment]
because i read to fast before answsering... the video lags and you only get sound from streamer, it must be his fault

**Comment by dextisol** [comment]
I see...

**Comment by Baussau** [comment]
It's not a bug. Most streamers use some tool so that their VODs don't contain the background music they use during their streams. In that way, they can avoid DMCA strikes on their VODs.
