### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by AymanL** [besuper/TwitchNoSub#88]
**Describe the bug**
The extension doesn't allow to view without being sub anymore

**VOD / Channel link**
All of them

**Browser**
Chrome and Brave, ...

**Additional context**
Thank you for your work

**Comment by AymanL** [comment]
Tried to remove and reinstall it still not allowing replays

**Comment by FirenzeIT** [comment]
Hello @besuper, i have too this bug and not resolve with uninstall and re-install, it's need to fix them... 

service worker (not enable/active), always this... and on twitch never works for this bug.

![Screenshot (20)](https://github.com/besuper/TwitchNoSub/assets/113168067/66f03792-249c-422d-8037-8a9536216818)

**Comment by besuper** [comment]
Hi, it's maybe v3 manifest, I will look into that. Have you tried with firefox (it's v2 manifest)?

**Comment by FirenzeIT** [comment]
Hi, yes i just tried with Firefox last updated too, same results..

Il Mer 20 Dic 2023, 12:55 Jayson ***@***.***> ha scritto:

**Comment by AymanL** [comment]
Fixed by the new 0.7 version 👍
