### ISSUE TITLE
Stopped working recently on Firefox

### ISSUE THREAD

**Issue by Bsd-us** [besuper/TwitchNoSub#92]
**Describe the bug**
Network Error 2000 when launching sub only videos

**VOD / Channel link**
Any sub only video (tested a few different channels and such)

**Browser**
Firefox 122.0.1 w10 64bits

**Additional context**
None

**Comment by Bsd-us** [comment]
Also, been a bit straight, but ty sm for your project it is very appreciated

**Comment by rasmu31** [comment]
I had this problem, I disabled ublock, accessed VOD and enabled again ublock. I didin't have this problem since.
https://github.com/besuper/TwitchNoSub/issues/77

Try enable/disable other extensions and retry access VOD.

**Comment by Bsd-us** [comment]
I don't know why but after retry today it worked again so I guess it is fixed ?
*I didn't test rasmu31 solution*
