### ISSUE TITLE
this doesn't work anymore

### ISSUE THREAD

**Issue by Ntha1** [besuper/TwitchNoSub#93]
**Describe the bug**

**VOD / Channel link**
The url where you encountered the error

**Browser**
Chrome, Edge, Firefox, Brave, ...

**Additional context**

**Comment by Peyonidas** [comment]
Doesn't on Chrome but still works on Firefox

**Comment by xarlsss** [comment]
Hello, I used the extension a few months ago and everything is fine until now the direct message only for subscribers appears again... I uninstalled it, installed it and it's still the same.

**Comment by alexiszev** [comment]
same on opera :(

**Comment by zankmaurice** [comment]
same here on Chrome, I really hope that this will be corrected/updated soon, I really appreciate this extension, I would be so down if it disappeared

**Comment by Endymi0n74** [comment]
works on firefox / edge

**Comment by acexae** [comment]
worked fine on firefox yesterday but doesn't work anymore on any vod

**Comment by 0sryder** [comment]
No longer works on edge, for me

**Comment by acexae** [comment]
update : works on firefox in incognito mode for whatever reason

**Comment by 0sryder** [comment]
Hello,
Here's a link to a VOD that doesn't work for me
[https://www.twitch.tv/videos/2112631244](url)

**Comment by Endymi0n74** [comment]
> Hello, Here's a link to a VOD that doesn't work for me [https://www.twitch.tv/videos/2112631244](url)

tested with edge and firefox. it works, i forgot about Hugo :D
![msedge_kLMJExVfS3](https://github.com/besuper/TwitchNoSub/assets/102302606/90bbf5dc-4510-48e5-8a97-bdbcb44d0874)

**Comment by Shryce** [comment]
Same issue.. doesn't work any more on Chrome and Edge (normal browser and inprivate/incognito)

**Comment by testhake** [comment]
It works in incognito mode because any incompatible extensions are also disabled, in my case, using chrome, it was the TTV LOL extension preventing this one from working. Once disabled, this one started working again, if you have it, or any other ad blocker extension for twitch, try disabling them.

**Comment by acexae** [comment]
> It works in incognito mode because any incompatible extensions are also disabled, in my case, using chrome, it was the TTV LOL extension preventing this one from working. Once disabled, this one started working again, if you have it, or any other ad blocker extension for twitch, try disabling them.

i tried disabling every extensions i have on normal mode but it doesn't work. it still does in incognito mode tho

**Comment by acexae** [comment]
> > Oh, it works for you. I didn't expect you to know Hugo :D
> 
> how did you install it so we see why it doesn't work ![msedge_5zbUe03B3l](https://private-user-images.githubusercontent.com/102302606/321316204-9ed3de25-812b-4eaa-829c-c613ced26a38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjgwOTEsIm5iZiI6MTcxMjc2Nzc5MSwicGF0aCI6Ii8xMDIzMDI2MDYvMzIxMzE2MjA0LTllZDNkZTI1LTgxMmItNGVhYS04MjljLWM2MTNjZWQyNmEzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxNjQ5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjE3YWI1OTA0MTcwYzk2NmE0Y2Q0ZjkxZDExYzExZWU4MWViZjE2ZTQzZDIzZDE3ODcwNjI2OTg5YjkzOGM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zZ22jYMAsoJean5_uTSP3xqkdSHMXXFqgl7ThcUZQU8)

mine for exemple 
![Capture d’écran (36)](https://github.com/besuper/TwitchNoSub/assets/166596678/4492fbff-c771-40b1-ba11-3a05a0224465)

**Comment by testhake** [comment]
> > It works in incognito mode because any incompatible extensions are also disabled, in my case, using chrome, it was the TTV LOL extension preventing this one from working. Once disabled, this one started working again, if you have it, or any other ad blocker extension for twitch, try disabling them.
> 
> i tried disabling every extensions i have on normal mode but it doesn't work. it still does in incognito mode tho

Did you try restarting firefox in normal mode after disabling the extensions?

**Comment by Endymi0n74** [comment]
> > > Oh, it works for you. I didn't expect you to know Hugo :D
> > 
> > 
> > how did you install it so we see why it doesn't work ![msedge_5zbUe03B3l](https://private-user-images.githubusercontent.com/102302606/321316204-9ed3de25-812b-4eaa-829c-c613ced26a38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjgwOTEsIm5iZiI6MTcxMjc2Nzc5MSwicGF0aCI6Ii8xMDIzMDI2MDYvMzIxMzE2MjA0LTllZDNkZTI1LTgxMmItNGVhYS04MjljLWM2MTNjZWQyNmEzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxNjQ5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjE3YWI1OTA0MTcwYzk2NmE0Y2Q0ZjkxZDExYzExZWU4MWViZjE2ZTQzZDIzZDE3ODcwNjI2OTg5YjkzOGM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zZ22jYMAsoJean5_uTSP3xqkdSHMXXFqgl7ThcUZQU8)
> 
> mine for example ![Capture d’écran (36)](https://private-user-images.githubusercontent.com/166596678/321331181-4492fbff-c771-40b1-ba11-3a05a0224465.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Njk2ODAsIm5iZiI6MTcxMjc2OTM4MCwicGF0aCI6Ii8xNjY1OTY2NzgvMzIxMzMxMTgxLTQ0OTJmYmZmLWM3NzEtNDBiMS1iYTExLTNhMDVhMDIyNDQ2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxNzE2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODAzMjRmY2YwOGFiYTQ2MzdiOTBiNWY4ZmUxODljMmUyMmViMGJlNzdmMjE2ZTRkNzYyYjgzYWI5ZjNiMmVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KujBIRAp_78cb7Mcp9ysnKpLEC6GRxCezLIYZV0-EkY)

yeah so nothing special :(

**Comment by 0sryder** [comment]
> > Oh, ça marche pour vous. Je ne m’attendais pas à ce que vous connaissiez Hugo :D
> 
> Comment l’avez-vous installé pour que nous voyions pourquoi cela ne fonctionne pas ![msedge_5zbUe03B3l](https://private-user-images.githubusercontent.com/102302606/321316204-9ed3de25-812b-4eaa-829c-c613ced26a38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Njk0NTUsIm5iZiI6MTcxMjc2OTE1NSwicGF0aCI6Ii8xMDIzMDI2MDYvMzIxMzE2MjA0LTllZDNkZTI1LTgxMmItNGVhYS04MjljLWM2MTNjZWQyNmEzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxNzEyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2E5OWM4MDNmMDc3YjA3Y2VmNDBkYWNkY2FjZDg5MDdkZTk2M2Q5MDhlNjFmMTYzOTIzZDk4NGVmN2RjYzEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hxbqav7FxF3M6eBW98V6BinbhjCpztQLZHwWTZLnrQU)

Here is my installation 
![Capture d'écran 2024-04-10 191623](https://github.com/besuper/TwitchNoSub/assets/20020601/72080f2c-2306-4780-9c9a-b4a230470f75)

**Comment by 0sryder** [comment]
I've deactivated all my extensions but it still doesn't work, except in incognito mode.

**Comment by acexae** [comment]
> > > It works in incognito mode because any incompatible extensions are also disabled, in my case, using chrome, it was the TTV LOL extension preventing this one from working. Once disabled, this one started working again, if you have it, or any other ad blocker extension for twitch, try disabling them.
> > 
> > 
> > i tried disabling every extensions i have on normal mode but it doesn't work. it still does in incognito mode tho
> 
> Did you try restarting firefox in normal mode after disabling the extensions?

yes but it doesn't work either

**Comment by JuliusCor** [comment]
It worked for me about 1 hour ago on chrome. Since then it no longer works. The only way to make it work is private browsing on Firefox, everything else is impossible.

**Comment by hozoruuuu** [comment]
deleting cookies for twitch.com made it work again for me on firefox

**Comment by aw6cd1a6** [comment]
It still work. but if this extension were to be blocked/banned or patched by Twitch,
really, I wouldn't be surprised. because there are plenty of stupid kid guy attempting to boast by sharing title a clip 
" I'm Hack Twitch! / Free Watch Sub Only VODs on Twitch! / I'm Hacker man 🤣 " on YouTube/Social. something like that :)
If it doesn't work in the future, it's nothing surprising.

**Comment by juliocoliveira** [comment]
Not working in firefox.

**Comment by Kikubay** [comment]
Just log out of your account and good job, you've solved this problem lmao

**Comment by juliocoliveira** [comment]
> Just log out of your account and good job, you've solved this problem lmao

I just did that, and it does not fix it. (Deleted all cookies)

**Comment by Resxt** [comment]
I can confirm clearing cookies for twitch.tv and reloading the page does work, even without private window (on Firefox)
Thanks @hozoruuuu

**Comment by 0sryder** [comment]
this solution doesn't work on edge, in any case for me the only one that works is incognito mode.

**Comment by acexae** [comment]
> deleting cookies for twitch.com made it work again for me on firefox

thanks it worked for me too

**Comment by Shryce** [comment]
Clearing all twitch.tv cookies in Edge (and restarting browser) does NOT work.

**Comment by Mister-NN** [comment]
it works on chrome and opera:

You must go to the padlock then to cookies and site data then close access to all sites.
you can then refresh, start again if it doesn't work

![image_2024-04-11_115855352](https://github.com/besuper/TwitchNoSub/assets/166706510/9e2195a2-8e08-4639-8df9-626f023c51a4)
![image_2024-04-11_115933056](https://github.com/besuper/TwitchNoSub/assets/166706510/0c16a2f1-aba6-4818-ad3d-30f891b68efe)
![image_2024-04-11_115940568](https://github.com/besuper/TwitchNoSub/assets/166706510/b7e9835a-1196-4266-9f1e-c9c914267992)

**Comment by 0sryder** [comment]
After 10 times, it finally worked (edge). it's strange.

**Comment by besuper** [comment]
Please update to https://github.com/besuper/TwitchNoSub/releases/tag/0.7.1

**Comment by Lio666** [comment]
it does't work for me (i have 0.9.1) and it keeps loading but not start the vod
