### ISSUE TITLE
Not working anymore on chrome, but working one Firefox and Edge.

### ISSUE THREAD

**Issue by UrbainN1** [besuper/TwitchNoSub#95]
**Describe the bug**

**VOD / Channel link**
The url where you encountered the error

**Browser**
Chrome, Edge, Firefox, Brave, ...

**Additional context**

**Comment by CantCode023** [comment]
i use opera gx, all i did was clear the cookies and it worked again.

**Comment by Maxxren** [comment]
> i use opera gx, all i did was clear the cookies and it worked again.

Deleting cookies doesn't work for me. I've tested it on two different PCs with different web browsers, but there's been no change

**Comment by besuper** [comment]
Please update to https://github.com/besuper/TwitchNoSub/releases/tag/0.7.1
