### ISSUE TITLE
doesent work

### ISSUE THREAD

**Issue by skYNoxchi** [besuper/TwitchNoSub#97]
**Describe the bug**

**VOD / Channel link**
The url where you encountered the error

**Browser**
Chrome, Edge, Firefox, Brave, ...

**Additional context**

**Comment by kevindjeradi** [comment]
If you clear the cookies it should work again, for now

**Comment by besuper** [comment]
Please update to https://github.com/besuper/TwitchNoSub/releases/tag/0.7.1
